import{a as y,S as w,i as n}from"./assets/vendor-CRCB-GUD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&o(g)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const h=a=>`
  <li class="gallery-card"><a class="gallery-link" href="${a.largeImageURL}">
    <img class="gallery-img" src="${a.webformatURL}" alt="${a.tags}"/>
</a><div class ="card-data">  <ul class="data-list"><li class="image-data"><p class="image-data-text">Views</p><p class="image-data-text">${a.views}</p></li>
  <li class="image-data"><p class="image-data-text">Likes</p><p class="image-data-text">${a.likes}</p></li>
  <li class="image-data"><p class="image-data-text">Comments</p><p class="image-data-text">${a.comments}</p></li>
  <li class="image-data"><p class="image-data-text">Downloads</p><p class="image-data-text">${a.downloads}</p></li>
  </ul></div></li>
  `;y.defaults.baseURL="https://pixabay.com/";const f=(a,t)=>{const r={params:{key:"45764445-59cc1762e95f1291ab4a968b5",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}};return y.get("api/",r)},d=document.querySelector(".search-form"),p=document.querySelector(".gallery"),l=document.querySelector(".loader"),i=document.querySelector(".js-load-more");let u="",m=1,L=0,c=0;const v=new w(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250}),b=async a=>{try{if(a.preventDefault(),m=1,c=0,u=d.elements.user_query.value.trim(),i.classList.contains("is-hidden")||i.classList.add("is-hidden"),u===""){n.show({message:"❌ Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}l.classList.add("is-open");const t=await f(u,m);if(t.data.total===0){l.classList.remove("is-open"),d.reset(),n.show({message:"❌ Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),p.innerHTML="";return}const r=t.data.hits.map(e=>h(e)).join("");if(d.reset(),l.classList.remove("is-open"),p.innerHTML=r,v.refresh(),L=p.querySelector("li").getBoundingClientRect().height,c=document.querySelectorAll(".gallery-card"),t.data.totalHits===c.length){n.show({message:"That's all we could find on your request",color:"yellow",position:"topRight"});return}i.classList.remove("is-hidden")}catch(t){console.log(t)}},q=async a=>{try{m+=1,l.classList.add("is-open");const t=await f(u,m),r=t.data.hits.map(o=>h(o)).join("");p.insertAdjacentHTML("beforeend",r),v.refresh(),l.classList.remove("is-open"),scrollBy({top:L*2,behavior:"smooth"}),c=document.querySelectorAll(".gallery-card"),t.data.totalHits<c.length&&(i.classList.add("is-hidden"),n.show({message:"We're sorry, but you've reached the end of search results.",color:"yellow",position:"topRight"}))}catch(t){console.log(t)}};d.addEventListener("submit",b);i.addEventListener("click",q);
//# sourceMappingURL=index.js.map
